# Generated by Django 3.2.8 on 2022-02-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=2, max_length=225),
            preserve_default=False,
        ),
    ]
